### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Keksstar** [GuildTV/ccg-bitc#1]
Hi!

When trying to open the overlay in the browser or via Caspar, the error: "Cannot GET /" occurs.
Happens on Caspar 2.1.0.3437 Beta 2

Any idea for an fix?

**Comment by Julusian** [comment]
Yes, this was a known problem with the packager not including the assets properly due to a misconfiguration.
The https://github.com/GuildTV/ccg-bitc/releases/tag/v0.3.0 release resolves this
